[package]
name = "rust_study"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[[bin]]
name = "insert_insort"
path = "insert_insort.rs"

#name = "merge"
#path = "merge_insort.rs"
